# Generated by Django 4.1 on 2022-08-27 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 5, 38, 19, 149445, tzinfo=datetime.timezone.utc), verbose_name='Fecha de publicación'),
        ),
    ]
